<a href="https://colab.research.google.com/github/Cristiancperez/Code_in_class/blob/main/03_Data_Structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. What is Data structure?**

Data structure are like variable, they *save* information, the difference is that data structure can strore more than 1 value.

Formally, Date structure store a **sequence** of values which can be located with an index (sciling).


**Example:**

* List, Vectors and Matrices
* Databases.

Now, basic phyton suck. It lacks specialized tools. In this case, we need to install *numpy*


# **2. liner algebra - Numpy** 

## **2.1 What is numpy?**
Numpy ( or numerical phyton) is a colletion of funtions and methods to handle DS.

This library (downlown diferents extencions for a phyton) works very well with other libraries and it is very popular.

In [2]:
# Install library 

import numpy as np



## 2.2 Numpy arrays - vectors and matrices 

Objects arramged by row and columns, with these object you can sum and multiply 


*Example 1:*
Let be x_{1] and this a mathematical notation $x_1$

Let $a$ be a vector with 2 rows and 1 column:


\begin{equation}
a = \left[\begin{array}{c} a_{1} \\ a_{2}
    \end{array}\right]
\end{equation}

This is called a **COLUMN VECTOR**, and the dimension or shape is $(3,1)$ or $(2 \times1)$

* the column is always firts and the rows is before 

*Example 2:*

\begin{equation}
a = \left[\begin{array}{c} b_{1} & b_{2} & b_{3}
    \end{array}\right]
\end{equation}


This is called a **ROW VECTOR** and de dimension or shape is $(1,3)$ or $(1\times3)$

*Example 3:* 

A matrix has more than 1 row and more than 1 column.

Of course if the number of roes and columns are equal, it is called a *squared matrix*.

In general, lef $M$ be a matrix of dimensions $(n,m)$ or $(n\times m)$.


For the case of $n=3$ and $m=3$

\begin{equation}
M = \left[\begin{array}{c} 
m_{1,1} & m_{1,2} & m_{1,3} \\
m_{2,1} & m_{2,2} & m_{2,3} \\
m_{3,1} & m_{3,2} & m_{3,3} \\
    \end{array}\right]
\end{equation}

Now, all of this in code.

In [ ]:
# Example - Column Vector

a = np.array([[4], [5], [6]])
print(a)
print(a.shape)

[[4]
 [5]
 [6]]
(3, 1)


In [ ]:
# Example - Row Vector

b = np.array([[1, 2, 3]])
print(b)
print(b.shape)

[[1 2 3]]
(1, 3)


In [ ]:
# Example - Matrix 


M = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print(M)
print(M.shape)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


**A nice trick**

In [ ]:
# nr: store the number of rows
# nc: stores the number of columns
nr, nc = M.shape


**Size of DS**

In Python, *size* means the number of elements in a DS.

In [ ]:
M.size 

9

In [ ]:
# ONE WARNING 

z = 2
w = np.array([[2]])
print(type(z),type(w))


<class 'int'> <class 'numpy.ndarray'>


array([[1.]])

## 2.3 Slicing 

It is the same as string variable, only with minor modifications.

Let´s see: 

In [ ]:
# Extract the 1st element


## Column Vector 
print(a[0,0])
print(type(a[0,0]))


## Row Vector
print(b[0,0])
print(type(b[0,0]))


## Matriz
print(M[1,1])


4
<class 'numpy.int64'>
1
<class 'numpy.int64'>
5


In [ ]:
# Extract the last element

print('The last element of a row vector:', b[0,-1])
print('The last element of a column vector:', a[-1,0])
print('The last element of a matrix:', M[-1,-1])

The last element of a row vector: 3
The last element of a column vector: 6
The last element of a matrix: 9


In [ ]:
# Extract a subset 

## Column Vector
print(a[0:2])


# Row Vector
print(b[0,0:2])

#Matrix 
print(M[0:2,0:2])

[[4]
 [5]]
[1 2]
[[1 2]
 [4 5]]


## 2.4 Useful methods

### Zeros and Ones

### Random numbers

We are talking about probabilities, and of probabilistic distributions.

### Another creation  options

#### Uniform distribution over [0,1)


In [4]:
# A single value

np.random.rand()

0.6662815177065324

In [9]:
# Example - The coin toss
## Here we are going to simulate a coin toss

if np.random.rand() <= 0.5:
  print('head')
else:
  print('tails')

head


In [14]:
# Example 2 - Ranking

## The idea is to print 'Low' if the numbers is lower the 0.3
## print 'Average' if is between 0.3 and 0.7
## print 'High' if it is grater than 0.7

rnd = np.random.rand()

if rnd <= 0.3:
  print('Low', rnd)
elif rnd > 0.3 and rnd <= 0.7:
  print('Average', rnd)
else:
  print('High', rnd)

Average 0.40059010542355855


**Exercise**

Code the following game. Print the messege
'You win': if two coin tosse are heads and print 'You lose' otherwise.


In [35]:
# Solution

## First try (or attempt)

First_attempt = np.random.rand()

if First_attempt <= 0.5:
  print('head', First_attempt)
else:
  print('tails', First_attempt)

## Second try (or attempt)

Secund_attempt = np.random.rand()

if Secund_attempt <= 0.5:
  print('head', Secund_attempt)
else:
  print('tails', Secund_attempt)

if First_attempt <= 0.5 and Secund_attempt <= 0.5:

  print('You win!')
else:
  print('You lose!')


head 0.4707497893815481
head 0.06988916218428143
You win!
