<a href="https://colab.research.google.com/github/Cristiancperez/Code_in_class/blob/main/03_Data_Structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. What is Data structure?**

Data structure are like variable, they *save* information, the difference is that data structure can strore more than 1 value.

Formally, Date structure store a **sequence** of values which can be located with an index (sciling).


**Example:**

* List, Vectors and Matrices
* Databases.

Now, basic phyton suck. It lacks specialized tools. In this case, we need to install *numpy*


# **2. liner algebra - Numpy** 

## **2.1 What is numpy?**
Numpy ( or numerical phyton) is a colletion of funtions and methods to handle DS.

This library (downlown diferents extencions for a phyton) works very well with other libraries and it is very popular.

In [ ]:
# Install library 

import numpy as np



## 2.2 Numpy arrays - vectors and matrices 

Objects arramged by row and columns, with these object you can sum and multiply 


*Example 1:*
Let be x_{1] and this a mathematical notation $x_1$

Let $a$ be a vector with 2 rows and 1 column:


\begin{equation}
a = \left[\begin{array}{c} a_{1} \\ a_{2}
    \end{array}\right]
\end{equation}

This is called a **COLUMN VECTOR**, and the dimension or shape is $(3,1)$ or $(2 \times1)$

* the column is always firts and the rows is before 

*Example 2:*

\begin{equation}
a = \left[\begin{array}{c} b_{1} & b_{2} & b_{3}
    \end{array}\right]
\end{equation}


This is called a **ROW VECTOR** and de dimension or shape is $(1,3)$ or $(1\times3)$

*Example 3:* 

A matrix has more than 1 row and more than 1 column.

Of course if the number of roes and columns are equal, it is called a *squared matrix*.

In general, lef $M$ be a matrix of dimensions $(n,m)$ or $(n\times m)$.


For the case of $n=3$ and $m=3$

\begin{equation}
M = \left[\begin{array}{c} 
m_{1,1} & m_{1,2} & m_{1,3} \\
m_{2,1} & m_{2,2} & m_{2,3} \\
m_{3,1} & m_{3,2} & m_{3,3} \\
    \end{array}\right]
\end{equation}

Now, all of this in code.

In [ ]:
# Example - Column Vector

a = np.array([[4], [5], [6]])
print(a)
print(a.shape)

[[4]
 [5]
 [6]]
(3, 1)


In [ ]:
# Example - Row Vector

b = np.array([[1, 2, 3]])
print(b)
print(b.shape)

[[1 2 3]]
(1, 3)


In [ ]:
# Example - Matrix 


M = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print(M)
print(M.shape)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


**A nice trick**

In [ ]:
# nr: store the number of rows
# nc: stores the number of columns
nr, nc = M.shape


**Size of DS**

In Python, *size* means the number of elements in a DS.

In [ ]:
M.size 

9

In [ ]:
# ONE WARNING 

z = 2
w = np.array([[2]])
print(type(z),type(w))


<class 'int'> <class 'numpy.ndarray'>


array([[1.]])

## 2.3 Slicing 

It is the same as string variable, only with minor modifications.

Let´s see: 

In [ ]:
# Extract the 1st element


## Column Vector 
print(a[0,0])
print(type(a[0,0]))


## Row Vector
print(b[0,0])
print(type(b[0,0]))


## Matriz
print(M[1,1])


4
<class 'numpy.int64'>
1
<class 'numpy.int64'>
5


In [ ]:
# Extract the last element

print('The last element of a row vector:', b[0,-1])
print('The last element of a column vector:', a[-1,0])
print('The last element of a matrix:', M[-1,-1])

The last element of a row vector: 3
The last element of a column vector: 6
The last element of a matrix: 9


In [ ]:
# Extract a subset 

## Column Vector
print(a[0:2])


# Row Vector
print(b[0,0:2])

#Matrix 
print(M[0:2,0:2])

[[4]
 [5]]
[1 2]
[[1 2]
 [4 5]]


## 2.4 Useful methods

### Zeros and Ones

### Random numbers

We are talking about probabilities, and of probabilistic distributions.

### Another creation  options

#### Uniform distribution over [0,1)


In [ ]:
# A single value

np.random.rand()

0.6662815177065324

In [ ]:
# Example - The coin toss
## Here we are going to simulate a coin toss

if np.random.rand() <= 0.5:
  print('head')
else:
  print('tails')

head


In [ ]:
# Example 2 - Ranking

## The idea is to print 'Low' if the numbers is lower the 0.3
## print 'Average' if is between 0.3 and 0.7
## print 'High' if it is grater than 0.7

rnd = np.random.rand()

if rnd <= 0.3:
  print('Low', rnd)
elif rnd > 0.3 and rnd <= 0.7:
  print('Average', rnd)
else:
  print('High', rnd)

Average 0.40059010542355855


**Exercise**

Code the following game. Print the messege
'You win': if two coin tosse are heads and print 'You lose' otherwise.


In [ ]:
# Solution

## First try (or attempt)

First_attempt = np.random.rand()

if First_attempt <= 0.5:
  print('head', First_attempt)
else:
  print('tails', First_attempt)

## Second try (or attempt)

Secund_attempt = np.random.rand()

if Secund_attempt <= 0.5:
  print('head', Secund_attempt)
else:
  print('tails', Secund_attempt)

if First_attempt <= 0.5 and Secund_attempt <= 0.5:

  print('You win!')
else:
  print('You lose!')


head 0.4707497893815481
head 0.06988916218428143
You win!


In [ ]:
First_attempt  = np.random.rand()
Second_attempt = np.random.rand()
results        = np.array([['Heads','Tails']])
indx1          = int(round(First_attempt,0))
indx2          = int(round(Second_attempt,0))

if First_attempt <= 0.5 and Second_attempt <= 0.5:
  print('Head', First_attempt)
  print('Head', Second_attempt)
  print('You win!')

else: 
  print(results[0,indx1], First_attempt)
  print(results[0,indx2], Second_attempt)
  print('You lose!')

Heads 0.24827522293364568
Tails 0.5783606011190101
You lose!


In [ ]:
# One dimensional array

np.random.rand(4)

array([0.85038896, 0.84795263, 0.9217608 , 0.5459415 ])

In [ ]:
tries          = np.random.rand(2)
results        = np.array([['Heads','Tails']])
indx1          = int(round(tries[0],0))
indx2          = int(round(tries[1],0))

if tries[0] <= 0.5 and tries[1] <= 0.5:
  print('Head', tries[0])
  print('Head', tries[1])
  print('You win!')

else: 
  print(results[0,indx1], tries[0])
  print(results[0,indx2], tries[1])
  print('You lose!')

Tails 0.9794850463870691
Heads 0.055005676474176646
You lose!


In [ ]:
# Two dimensional arrays

np.random.rand(7,8)

array([[0.14604946, 0.67537592, 0.47768667, 0.64470287, 0.74746245,
        0.01786449, 0.18034044, 0.54964668],
       [0.49186188, 0.58954841, 0.44533039, 0.65695197, 0.34630896,
        0.61650685, 0.58284496, 0.33358863],
       [0.69868924, 0.50464381, 0.12465914, 0.42677561, 0.72845949,
        0.29954459, 0.8127837 , 0.91779925],
       [0.07325335, 0.45004093, 0.27709245, 0.42768441, 0.7837647 ,
        0.48910035, 0.96490014, 0.12592468],
       [0.2684272 , 0.16882972, 0.20702653, 0.78534743, 0.65981165,
        0.84667628, 0.65262908, 0.95945779],
       [0.05053573, 0.13178765, 0.64419252, 0.08679954, 0.3977318 ,
        0.52754818, 0.64205149, 0.77675612],
       [0.09664462, 0.48618018, 0.70475393, 0.26017201, 0.94662806,
        0.84785299, 0.69514338, 0.81413464]])

### Uniform distribution over [a,b)



In [ ]:
# One value
np.random.uniform(low = 3, high = 5)

4.179664597223741

In [ ]:
# One dimensional
np.random.uniform(low = -10, high = 0, size =10)

array([-9.264989  , -7.65741423, -0.7886224 , -8.01404116, -6.48609077,
       -0.96812101, -2.89335743, -1.21410243, -3.88468951, -0.47606115])

In [ ]:
# Two dimensional
np.random.uniform(low = 3, high = 5, size = (4,2))

array([[3.83005599, 3.63270237],
       [4.13068975, 3.13789289],
       [3.71448146, 3.25924454],
       [4.69847465, 4.77276399]])

### Normal Distribution



In [ ]:
# Standard Noraml - N ~ (0,1)

np.random.randn()
np.random.randn(8)
np.random.randn(7,5)

array([[-1.61478041,  1.25565383,  0.46552951,  0.98110702, -0.0335673 ],
       [-1.18607947, -0.04527932, -1.35927056, -1.18263347, -0.17879766],
       [ 0.06427539, -1.2082444 , -1.7015121 , -0.20381484, -0.09949221],
       [-0.82400795, -0.02685212,  0.5884883 , -0.29917591,  0.22267159],
       [-0.71821854,  0.66198508,  0.25061795,  0.66453703,  0.80292066],
       [-0.78720369,  1.61521403,  0.29013996,  0.29382219, -1.29224162],
       [ 1.54778926, -1.20719576,  1.92083882,  0.3056111 ,  1.04533897]])

In [ ]:
# Normal - N ~ (mu,sigma)

mu    = 0.001  # mean
sigma = 0.1    # std. deviation

np.random.normal(mu, sigma)
np.random.normal(mu, sigma, size = 5)
np.random.normal(mu, sigma, size = (3,1))

array([[-0.00854717],
       [-0.07543896],
       [-0.02653613]])

### Random Integer 



In [ ]:
np.random.randint(low = 0, high = 10) # one value 
np.random.randint(low = 0, high = 10, size = 8) # one dimension
np.random.randint(low = 0, high = 10, size = (3,2)) # two dimension


array([[1, 3],
       [9, 4],
       [7, 2]])

## Exercise 1


In [ ]:
number = 5 # example 

'Even' if (number % 2) == 0 else 'Odd'

'Odd'

In [ ]:
Bet_a_number  = 17
Neutro        = (0)
Red  = np.array([1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36])
Black = np.array([2,4,6,8,10,11,13,15,17,20,22,24,26,28,29,31,33,35])
number       = np.random.randint(low = 0, high = 37)
print('Bet:', Bet_a_number, 'Black')
if number == Bet_a_number:
  print('Result:', number,',You win!')
else:
  print('Result:', number,',You loset!')




Bet: 17 Black
Result: 12 ,You loset!


In [ ]:
Bet_a_number = 17
print('Bet:', Bet_a_number, 'Black')
number       = np.random.randint(low = 0, high = 37)
'You win!' if (number % 2) == 0 else 'You Loset!'

Bet: 17 Black


'You Loset!'